spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.100.250:3306/openapi_business?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: shujuku@Dayi
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle\u9700\u8981\u6253\u5f00\u6ce8\u91ca
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true

    redis:
       open: true  # \u662f\u5426\u5f00\u542fredis\u7f13\u5b58  true\u5f00\u542f   false\u5173\u95ed
       database: 3
       host: dev-redis.tae-tea.net
       port: 6379
       password: ivYs9ryid7zUeku    # \u5bc6\u7801\uff08\u9ed8\u8ba4\u4e3a\u7a7a\uff09
       timeout: 6000ms  # \u8fde\u63a5\u8d85\u65f6\u65f6\u957f\uff08\u6beb\u79d2\uff09
       jedis:
         pool:
           max-active: 1000  # \u8fde\u63a5\u6c60\u6700\u5927\u8fde\u63a5\u6570\uff08\u4f7f\u7528\u8d1f\u503c\u8868\u793a\u6ca1\u6709\u9650\u5236\uff09
           max-wait: -1ms      # \u8fde\u63a5\u6c60\u6700\u5927\u963b\u585e\u7b49\u5f85\u65f6\u95f4\uff08\u4f7f\u7528\u8d1f\u503c\u8868\u793a\u6ca1\u6709\u9650\u5236\uff09
           max-idle: 10      # \u8fde\u63a5\u6c60\u4e2d\u7684\u6700\u5927\u7a7a\u95f2\u8fde\u63a5
           min-idle: 5       # \u8fde\u63a5\u6c60\u4e2d\u7684\u6700\u5c0f\u7a7a\u95f2\u8fde\u63a5

dubbo:
    application:
      name: yestae-openapi-consumer
    registry:
      address: dev-zk-1.tae-tea.net:2181,dev-zk-2.tae-tea.net:2181,dev-zk-3.tae-tea.net:2181
yestae:
  sms:
    defaultExpires: 1800
    smsOpen: true
    smsPlatform: HOAQZTSPCXI
    smsUrl: https://sms-api-test.yestae.com/sms-api
    
  vas:
    zx: af650e3e0a024bed8384ec419f93d1f0
    